### PR TITLE
Format Go imports

### PR DESCRIPTION
**Pull request by ccoVeille**
Fixed by running the following command:

```shell
gci write -s standard -s default -s 'prefix(github.com/theredditbandit/pman)' .
```

`gci` can be found here https://github.com/daixiang0/gci

### CODE REVIEW

**Review by theredditbandit — APPROVED** [review]

**Comment by theredditbandit** [comment]
This tool is awesome , I should add it as a git hook to keep imports consistent going forward.

**Comment by ccoVeille** [comment]
> This tool is awesome , I should add it as a git hook to keep imports consistent going forward.

Well, if you are using gopls, directly or via vs code, you can set it up directly without the tool.

Do you? If so, I can look for the settings I used ages ago

I will have to write something on my https://dev.to/ccoveille

**Comment by theredditbandit** [comment]
I am using gopls as my lsp, I have it setup in my neovim config like this.
image

and this formats the code quite well but when it comes to imports it starts acting weird , I'll show you

---
This is how the imports in [cmd/delete.go](https://github.com/theredditbandit/pman/blob/7981219ce1fe72a891f117180f670b1b26e82334/cmd/delete.go) are formatted according to `gci` , and initially when I try to format it using gopls nothing changes.
image

but the moment I delete those spaces between imports and then format it using gopls , it completely changes the order of imports.

1. Spaces removed

image

2. Formatted with gopls
image

I don't understand why it changes the order of imports when spaces are deleted but it does.

**Comment by theredditbandit** [comment]
Thanks! , I'll add gofumpt to my lsp config right away. I think this also solves the import issue because gofumpt will also always have deterministic ordering of imports.

**Pull request merged**
